### ISSUE TITLE
Publicera på F-Droid

### ISSUE THREAD

**Issue by AntiSC2** [OAndell/Riksdagskollen#2]
Eftersom Riksdagskollen redan är open-source så skulle det vara bra om den fanns tillgänglig på F-Droid, en app store med bara open-source appar. Enligt mig så borde inte folk behöva gå igenom Google ifall de vill har mer koll på riksdagen.

Länk till hur man får sin app upplagd där:
https://f-droid.org/en/contribute/

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/3655

**Comment by gustavaa** [comment]
Väntar på publicering på f-droid.

**Comment by licaon-kter** [comment]
Reopen this.

Do add a Gradle flavour without non-free deps like Crashlytics.

Also, FYI: https://get.fabric.io/roadmap

**Comment by gustavaa** [comment]
@licaon-kter Decided to create a [new branch](https://github.com/OAndell/Riksdagskollen/tree/fdroid) of the app, completely free of non-free dependencies. What changes needs to be done in the metadata with this solution?

**Comment by gustavaa** [comment]
F-droid accepterade inte lösningen med en fdroid-specifik branch utan insisterade på att vi ska implementera två gradle flavours istället, varav en är helt fri från google-dependencies. Spenderade ett par timmar med att undersöka hur man kan åstadkomma detta men det finns ingen lösning jag känner mig nöjd med. Alla lösningar innebär att man i någon utsträckning måste dela upp källkoden i två olika versioner, vilket för oss inte är önskvärt. Eftersom efterfrågan av publicering på F-droid är förhållandevis liten, så kommer ingen av oss spendera mer tid på detta issue för tillfället. Med det sagt är vi alltid öppna för pull requests om någon har en bra lösning.

**Comment by licaon-kter** [comment]
And in english?

**Comment by gustavaa** [comment]
@licaon-kter 
We created an Fdroid branch, and sent a merge request for it to fetch updates from this branch by changing UpdateCheckMode to RepoManifest/fdroid which would have been a fine solution for our purpose I think. But we were requested to instead make an fdroid flavour with flavour dependencies, which is not a desirable solution for us as it requires us to maintain two versions of some classes that has analytics embedded inside. I could be missing something, but this was the only way I could make the fdroid flavour compile. 

As such, we have decided not to spend more time on trying to publish the app on Fdroid since the demand seems to be very small in relation to the number of users on Google play.

**Comment by gustavaa** [comment]
@AntiSC2 Update: After working with Fdroid to resolve the issues discussed above, Riksdagskollen is yet again available on Fdroid. We are sorry that it has taken so long.
